"use strict";
const path=require("path"),fs=require("fs"),http=require("http"),express=require("express");
const {Server}=require("socket.io");
const {TikTokBridge}=require("./tiktok-bridge");
let multer=null;try{multer=require("multer")}catch{}
const app=express(),httpServer=http.createServer(app),io=new Server(httpServer),PORT=process.env.PORT||3000;
const DB=path.join(__dirname,"data","questions.json"),UP=path.join(__dirname,"uploads"),RANKINGS=path.join(__dirname,"data","rankings.json");
fs.mkdirSync(UP,{recursive:true});fs.mkdirSync(path.dirname(DB),{recursive:true});
app.use(express.json());app.use(express.static(__dirname));
app.get("/",(_,r)=>r.sendFile(path.join(__dirname,"index.html")));
app.get("/admin",(_,r)=>r.sendFile(path.join(__dirname,"admin.html")));
if(multer){const storage=multer.diskStorage({destination:(_,__,cb)=>cb(null,UP),filename:(_,f,cb)=>cb(null,Date.now()+"-"+Math.random().toString(36).slice(2,8)+path.extname(f.originalname).toLowerCase())});const upload=multer({storage});app.post("/api/upload",upload.single("image"),(q,r)=>r.json({ok:!!q.file,path:q.file?"uploads/"+q.file.filename:""}))}
function loadQuestions(){try{return JSON.parse(fs.readFileSync(DB,"utf8"))}catch{return[]}}
function saveQuestions(q){fs.writeFileSync(DB,JSON.stringify(q,null,2),"utf8")}
function norm(q,i=0){const direct=Number(q.helyesAr),from=Number(q.valaszok?.[Number(q.helyes)||0]);return{id:q.id??Date.now()+i,termek:q.termek||q.nev||"",kep:q.kep||"",helyesAr:Number.isFinite(direct)&&direct>0?direct:from,nehezseg:Number(q.nehezseg)||1,kategoria:q.kategoria||"ÁrPárbaj"}}
function wrong(c){const step=c<1000?50:c<5000?100:c<20000?500:c<100000?1000:5000,s=new Set;while(s.size<3){const pct=.05+Math.random()*.15,sign=Math.random()<.5?-1:1;let v=Math.round(c*(1+sign*pct));v=Math.round(v/step)*step;if(v!==c)s.add(v)}return[...s]}
const tournament=new Map(),profiles=new Map(),roundAnswers=new Map(),giftMultiplier=new Map(),activePlayers=new Map(),playerNames=new Map();
let answerSeq=0;
function participant(d){const name=String(d?.name||d?.user||"Játékos").trim()||"Játékos",key=String(d?.user||name).trim().toLocaleLowerCase("hu-HU");if(!playerNames.has(key))playerNames.set(key,name);return{key,name:playerNames.get(key)}}
const topFromMap=m=>[...m.entries()].map(([key,v])=>({name:playerNames.get(key)||key,score:Number(v)||0,avatar:profiles.get(key)?.avatar||""})).sort((a,b)=>b.score-a.score||a.name.localeCompare(b.name)).slice(0,100);
const tournamentTop=()=>topFromMap(tournament);
function emitBoards(){io.emit("leaderboardUpdated",{players:tournamentTop(),activePlayerCount:activePlayers.size})}
function difficultyKey(n){n=Number(n)||1;return n>=5?"hard":n>=3?"medium":"easy"}
function basePoints(diff,place){const k=difficultyKey(diff);if(k==="easy")return Math.max(1,11-place);if(k==="medium")return Math.max(10,32-place*2);return Math.max(20,52-place*2)}
function giftConfig(diff){const k=difficultyKey(diff);if(k==="easy")return[{points:1,multiplier:2},{points:20,multiplier:3}]:k==="medium"?[{points:30,multiplier:2},{points:99,multiplier:3}]:[{points:99,multiplier:2},{points:299,multiplier:3}]}
function addTournament(player,pts,avatar=""){const {key}=typeof player==="string"?participant({name:player}):player;if(avatar)profiles.set(key,{avatar});tournament.set(key,(tournament.get(key)||0)+pts);emitBoards()}
function rankingData(){let r={daily:{},weekly:{},monthly:{},allTime:{}};try{const old=JSON.parse(fs.readFileSync(RANKINGS,"utf8"));r={...r,...old}}catch{}return r}
function periodKeys(){const now=new Date(),day=now.toISOString().slice(0,10),tmp=new Date(Date.UTC(now.getFullYear(),now.getMonth(),now.getDate()));const dn=tmp.getUTCDay()||7;tmp.setUTCDate(tmp.getUTCDate()+4-dn);const ys=new Date(Date.UTC(tmp.getUTCFullYear(),0,1));const wn=Math.ceil((((tmp-ys)/86400000)+1)/7);return{day,week:`${tmp.getUTCFullYear()}-W${String(wn).padStart(2,"0")}`,month:`${now.getFullYear()}-${String(now.getMonth()+1).padStart(2,"0")}`}}
function objTop(o){return Object.entries(o||{}).map(([name,v])=>({name,score:Number(v?.score??v)||0,avatar:v?.avatar||""})).sort((a,b)=>b.score-a.score||a.name.localeCompare(b.name)).slice(0,100)}
function rankingSnapshot(){const r=rankingData(),k=periodKeys();return{daily:objTop(r.daily?.[k.day]),weekly:objTop(r.weekly?.[k.week]),monthly:objTop(r.monthly?.[k.month]),allTime:objTop(r.allTime)}}
function emitPersistent(target=io){const d=rankingSnapshot();target.emit("persistentRankings",d);target.emit("allTimeTop3",{players:d.allTime.slice(0,3)})}
function saveRankings(){const r=rankingData(),k=periodKeys();r.daily=r.daily||{};r.weekly=r.weekly||{};r.monthly=r.monthly||{};r.allTime=r.allTime||{};r.daily[k.day]=r.daily[k.day]||{};r.weekly[k.week]=r.weekly[k.week]||{};r.monthly[k.month]=r.monthly[k.month]||{};const add=(bucket,p)=>{const n=p.name||"Ismeretlen";bucket[n]=bucket[n]||{score:0,avatar:p.avatar||""};bucket[n].score=(Number(bucket[n].score)||0)+(Number(p.score)||0);if(p.avatar)bucket[n].avatar=p.avatar};tournamentTop().forEach(p=>{add(r.daily[k.day],p);add(r.weekly[k.week],p);add(r.monthly[k.month],p);add(r.allTime,p)});fs.writeFileSync(RANKINGS,JSON.stringify(r,null,2),"utf8");emitPersistent()}
let S={running:false,paused:false,countdown:20,between:3,max:10,index:-1,num:0,round:0,q:null,a:[],closed:true,deadline:0,remaining:0,roundTimer:null,nextTimer:null,autoMode:false};
function clearTimers(){if(S.roundTimer)clearTimeout(S.roundTimer);if(S.nextTimer)clearTimeout(S.nextTimer);S.roundTimer=S.nextTimer=null}
function remainingSeconds(){return S.paused?S.remaining:Math.max(0,Math.ceil((S.deadline-Date.now())/1000))}
function payload(){return{question:{...S.q,answers:S.a.map(x=>({answerId:x.letter,letter:x.letter,price:x.price}))},countdown:remainingSeconds()||S.countdown,questionNumber:S.num,maxQuestions:S.max,roundId:S.round,activePlayerCount:activePlayers.size,giftRules:giftConfig(S.q?.nehezseg||1),autoMode:S.autoMode}}
function scheduleRound(ms){S.remaining=Math.max(0,Math.ceil(ms/1000));S.deadline=Date.now()+ms;S.roundTimer=setTimeout(()=>closeRound(),ms)}
function shuffleArray(arr){const a=[...arr];for(let i=a.length-1;i>0;i--){const j=Math.floor(Math.random()*(i+1));[a[i],a[j]]=[a[j],a[i]]}return a}
function next(){clearTimers();if(!S.running||S.paused)return;let qs=loadQuestions().map(norm).filter(q=>q.termek&&q.helyesAr>0);if(!qs.length)return io.emit("gameMessage",{message:"⚠️ Nincs érvényes termék."});if(S.num>=S.max)return finishTournament();const remaining=qs.slice(S.index+1);if(remaining.length===0){const shuffled=shuffleArray(qs);S.q=shuffled[0];S.a=[{price:S.q.helyesAr,ok:true},...wrong(S.q.helyesAr).map(price=>({price,ok:false}))];const pool="ABCDEFGHJKMNPRSTUVWXYZ".split("");const shuffledPool=shuffleArray(pool);S.a.forEach((x,i)=>x.letter=shuffledPool[i]);S.round++;S.num++;S.closed=false;S.paused=false;answerSeq=0;roundAnswers.clear();giftMultiplier.clear();S.remaining=S.countdown;io.emit("questionStarted",{...payload(),countdown:S.countdown});scheduleRound(S.countdown*1000)}else{const shuffled=shuffleArray(remaining);S.q=shuffled[0];S.a=[{price:S.q.helyesAr,ok:true},...wrong(S.q.helyesAr).map(price=>({price,ok:false}))];const pool="ABCDEFGHJKMNPRSTUVWXYZ".split("");const shuffledPool=shuffleArray(pool);S.a.forEach((x,i)=>x.letter=shuffledPool[i]);S.round++;S.num++;S.index=qs.indexOf(S.q);S.closed=false;S.paused=false;answerSeq=0;roundAnswers.clear();giftMultiplier.clear();S.remaining=S.countdown;io.emit("questionStarted",{...payload(),countdown:S.countdown});scheduleRound(S.countdown*1000)}}
function submitAnswer(d,reply){const validAnswerIds=S.a.map(x=>x.answerId||x.letter);if(process.env.DEBUG_TEST_ANSWERS==="1")console.log("[testAnswer] fogadott payload:",d,"| érvényes answerId-k:",validAnswerIds);if(!S.running)return reply?.({ok:false,message:"Nincs futó játék."});if(S.paused)return reply?.({ok:false,message:"A játék szünetel."});if(S.closed)return reply?.({ok:false,message:"A forduló lezárult."});const player=participant(d),answerId=String(d?.answerId??d?.letter??"").trim().toUpperCase();if(roundAnswers.has(player.key))return reply?.({ok:false,message:"Ez a játékos már válaszolt."});const choice=S.a.find(x=>(x.answerId||x.letter)===answerId);if(!choice){if(process.env.DEBUG_TEST_ANSWERS==="1")console.warn("[testAnswer] elutasítva: answerId nincs az aktuális kérdésben:",answerId);return reply?.({ok:false,message:"Érvénytelen válaszazonosító."})}answerSeq++;roundAnswers.set(player.key,{...player,letter:answerId,correct:!!choice.ok,seq:answerSeq,points:0,avatar:d?.avatar||""});if(d?.avatar)profiles.set(player.key,{avatar:d.avatar});activePlayers.set(player.key,{...player,avatar:d?.avatar||profiles.get(player.key)?.avatar||""});io.emit("answerAccepted",{name:player.name,letter:answerId,roundId:S.round,activePlayerCount:activePlayers.size});reply?.({ok:true,message:`${player.name} válasza elfogadva: ${answerId}`,roundId:S.round,activePlayerCount:activePlayers.size})}
function closeRound(){if(!S.running||S.paused||S.closed)return;clearTimers();S.closed=true;const correct=S.a.find(x=>x.ok)?.letter,winners=[...roundAnswers.values()].filter(x=>x.correct).sort((a,b)=>a.seq-b.seq);winners.forEach((x,i)=>{const base=basePoints(S.q.nehezseg,i+1),mult=giftMultiplier.get(x.key)||1;x.points=base*mult;addTournament(x,x.points,x.avatar)});const results=[...roundAnswers.values()].sort((a,b)=>a.seq-b.seq).map(x=>({name:x.name,letter:x.letter,correct:x.correct,score:x.points,multiplier:giftMultiplier.get(x.key)||1}));const roundTop=winners.map((x,i)=>({name:x.name,score:x.points,avatar:x.avatar||profiles.get(x.key)?.avatar||"",base:basePoints(S.q.nehezseg,i+1),multiplier:giftMultiplier.get(x.key)||1})).slice(0,25);io.emit("roundEnded",{correctLetter:correct,correctPrice:S.q.helyesAr,between:S.between,roundRanking:roundTop,tournamentRanking:tournamentTop(),answerResults:results,questionNumber:S.num,maxQuestions:S.max});S.nextTimer=setTimeout(()=>{if(S.running&&!S.paused){if(S.num>=S.max)finishTournament();else next()}},S.between*1000)}
function finishTournament(){clearTimers();saveRankings();S.running=false;S.closed=true;const players=tournamentTop();const top3=players.slice(0,3);while(top3.length<3)top3.push({name:"—",score:0,avatar:""});io.emit("tournamentEnded",{top3,players})}
function applyGift(d){if(!S.running||S.paused||S.closed)return;const player=participant(d),value=Number(d?.points??d?.coins??0),rules=giftConfig(S.q?.nehezseg||1);const mult=value>=rules[1].points?3:value>=rules[0].points?2:1;if(mult>1)giftMultiplier.set(player.key,Math.max(giftMultiplier.get(player.key)||1,mult));return{player,value,mult}}
const tiktokBridge=new TikTokBridge(io,{onAnswer:d=>submitAnswer(d),onGift:d=>applyGift(d)});
io.on("connection",s=>{
  s.emit("gameState",{running:S.running,paused:S.paused,countdown:remainingSeconds(),between:S.between,questionNumber:S.num,maxQuestions:S.max,autoMode:S.autoMode});s.emit("leaderboardUpdated",{players:tournamentTop()});emitPersistent(s);if(S.running&&S.q&&!S.closed)s.emit("questionStarted",payload());
  s.on("startGame",d=>{clearTimers();S.running=true;S.paused=false;S.countdown=Math.max(3,+d?.countdown||20);S.between=Math.max(1,+d?.between||3);S.max=Math.max(1,+d?.maxQuestions||10);S.autoMode=!!d?.autoMode;S.index=-1;S.num=0;S.closed=true;tournament.clear();profiles.clear();playerNames.clear();roundAnswers.clear();giftMultiplier.clear();activePlayers.clear();emitBoards();io.emit("tournamentStarted");next()});
  s.on("pauseGame",()=>{if(!S.running||S.paused)return;S.remaining=remainingSeconds();S.paused=true;clearTimers();io.emit("gamePaused",{remaining:S.remaining})});
  s.on("resumeGame",()=>{if(!S.running||!S.paused)return;S.paused=false;io.emit("gameResumed",{remaining:S.remaining,roundId:S.round});if(!S.closed){io.emit("questionResumed",{remaining:S.remaining,roundId:S.round});scheduleRound(S.remaining*1000)}else if(S.autoMode){S.nextTimer=setTimeout(()=>{if(S.running&&!S.paused){if(S.num>=S.max)finishTournament();else next()}},Math.max(1,S.between)*1000)}});
  s.on("stopGame",()=>{S.running=false;S.closed=true;S.paused=false;clearTimers();io.emit("gameStopped")});
  s.on("timeExpired",d=>{if(S.closed)return;if(Number(d?.roundId)!==S.round)return;closeRound()});
  s.on("nextQuestion",()=>closeRound());
  s.on("testAnswer",(d,ack)=>submitAnswer(d,ack));
  s.on("playerAnswer",d=>submitAnswer(d));s.on("tiktokAnswer",d=>submitAnswer(d));
  s.on("simulatePlayer",d=>addTournament(d?.name||"Teszt játékos",Number(d?.points)||10,d?.avatar||""));
  s.on("giftReceived",d=>{const result=applyGift(d);if(result?.mult>1)io.emit("giftEffect",{user:result.player.name,points:result.value,multiplier:result.mult})});
  s.on("getGiftRules",()=>s.emit("giftRules",giftConfig(S.q?.nehezseg||1)));s.on("getPersistentRankings",()=>emitPersistent(s));
  s.on("connectTikTok",async d=>{console.log("[SERVER] connectTikTok esemény megérkezett:", d);try{console.log("[SERVER] TikTokBridge.connect indul");await tiktokBridge.connect(d?.username);console.log("[SERVER] TikTokBridge.connect sikeres");s.emit("adminMessage",{ok:true,message:"TikTok LIVE csatlakoztatva."})}catch(e){console.error("[SERVER] TikTokBridge hiba:", e);s.emit("adminMessage",{ok:false,message:e?.message||String(e)})}});s.on("disconnectTikTok",()=>tiktokBridge.disconnect());
  s.on("saveQuestion",d=>{const qs=loadQuestions().map(norm),q=norm({...d,id:Date.now()});if(!q.termek||!q.kep||!(q.helyesAr>0))return s.emit("adminMessage",{ok:false,message:"Hiányos adatok."});qs.push(q);saveQuestions(qs);io.emit("questionsUpdated",qs);s.emit("adminMessage",{ok:true,message:"✅ Termék elmentve."})});
  s.on("getQuestions",()=>s.emit("questionsUpdated",loadQuestions().map(norm)));s.on("deleteQuestion",id=>{const q=loadQuestions().map(norm).filter(x=>String(x.id)!==String(id));saveQuestions(q);io.emit("questionsUpdated",q)});
  s.on("showPodium",()=>io.emit("showPodiumManually",{top3:tournamentTop().slice(0,3)}));s.on("hidePodium",()=>io.emit("hidePodiumManually"));
  s.on("showRanking",d=>{const snap=rankingSnapshot();const data=snap[d?.type]||[];io.emit("showRankingOverlay",{type:d?.type,players:data})});s.on("hideRanking",()=>io.emit("hideRankingOverlay"));
});
httpServer.listen(PORT,()=>console.log(`\n🎮 ÁrPárbaj LIVE\nJáték: http://localhost:${PORT}\nAdmin: http://localhost:${PORT}/admin\n`));